FROM node:18

WORKDIR /usr/src/app
# WORKDIR /combos

ARG REACT_APP_API_BASE_URL
ARG REACT_APP_STORAGE_ACCOUNT_NAME
ARG REACT_APP_STORAGE_CONTAINER_NAME
ARG REACT_APP_STORAGE_ACCESS_KEY
ARG REACT_APP_SAS_URL
ARG REACT_APP_SAS_TOKEN


ENV REACT_APP_API_BASE_URL $REACT_APP_API_BASE_URL
ENV REACT_APP_STORAGE_ACCOUNT_NAME $REACT_APP_STORAGE_ACCOUNT_NAME
ENV REACT_APP_STORAGE_CONTAINER_NAME $REACT_APP_STORAGE_CONTAINER_NAME
ENV REACT_APP_STORAGE_ACCESS_KEY $REACT_APP_STORAGE_ACCESS_KEY
ENV REACT_APP_SAS_URL $REACT_APP_SAS_URL
ENV REACT_APP_SAS_TOKEN $REACT_APP_SAS_TOKEN

COPY package.json ./
COPY package-lock.json ./
COPY yarn.lock ./
COPY ./ ./
RUN yarn --network-timeout 100000

CMD ["yarn", "start"]